### ISSUE TITLE
Using MESC heritability mediated by genetic effects on splicing  

### ISSUE THREAD

**Issue by sbguarch** [douglasyao/mesc#2]
Hi, 

Is it possible to directly apply MESC to estimate trait/disease h2 mediated by genetic effects on splicing (instead of gene expression)?  So, instead of estimating individual expression scores, estimating individual splicing scores based on splicing ratios (intron ratios) from leafcutter? I tried but it's not working because REML can't converge. 

Thanks!

**Comment by douglasyao** [comment]
Hi,

In theory, there should be no issue estimating h2 mediated by molecular phenotypes other than expression using MESC. REML convergence issues are likely caused by small sample size of the splicing data set. For small QTL data sets (<100 samples, though this cutoff will depend on the heritability and polygenicity of the molecular phenotype), I'd advise against using MESC to estimate mediated h2, as downward biases can occur due to small sample size.

**Comment by sbguarch** [comment]
Hi, 

My sample size is ~400 so should it be fine, right? So, I had no issues with gene expression, is there any other tip that could explain this systematic error for all chr?

Many thanks!

**Comment by sbguarch** [comment]
Hi, 

Sorry, I've  just realised that there was an error in my covariate input file for the splicing analysis. Thank you for your quick feedback and everything runs smoothly. Sorry to bother you.

**Comment by douglasyao** [comment]
No problem, glad it works!
